### ISSUE TITLE
Making traversy cljs compatible

### ISSUE THREAD

**Issue by johncowie** [ctford/traversy#3]
There's very little to be done to make lens.clj cross-platform compatible.  However, Midje doesn't currently support cljs...

How would you feel if I replaced the tests with clojure.test?

You'd lose Midje's autotest, but it means that the same tests can be run against both clj and cljs to verify cross-platform support.  Also [lein-test-refresh](https://github.com/jakemcc/lein-test-refresh) looks like a decent prospect for retaining that autotest-y goodness.

**Comment by ctford** [comment]
Supporting CLJS would definitely be worth dropping Midje for. We don't use
any special Midje features anyway.

**Comment by johncowie** [comment]
I thought I was pushing my commits to a fork and then realised I wasn't.  Oops.  Anyway I think all is good.  The tests look a bit gross which is sad.  Ah well.
