### ISSUE TITLE
Wee typo in 'each' lens tests 

### ISSUE THREAD

**Issue by ghost** [ctford/traversy#6]
https://github.com/ctford/traversy/blob/master/test/traversy/test/lens.cljc#L52
Hey Chris,
I think
       (is (= (-> {:foo 3 :bar 4} (view each) set #{[:foo 3] [:bar 4]})))
should be 
       (is (= (-> {:foo 3 :bar 4} (view each) set) #{[:foo 3] [:bar 4]}))
?
Cheers, Andy

**Comment by ctford** [comment]
You're right! Good spot. Would you like to submit a pull request so that
you're listed as a contributor on Github?

**Comment by ghost** [comment]
Hey Chris, yes, good idea, I'll get right on it.

Cheers, Andy

**Comment by ctford** [comment]
Fixed by @CodingAnimal in #7.
