### ISSUE TITLE
Lack of distinction between absence of location, and nil value at location.

### ISSUE THREAD

**Issue by johncowie** [ctford/traversy#9]
Raising this issue in the context of some of the validation work I'm doing.

In a nutshell, sometimes I want to distinguish between the correctness of the structure of my data, and the values at the 'leaves' of the data.

E.g.  There might be a case where ```{}``` is invalid but ``` {:a nil}``` is not.  

_prismatic/schema_ makes this distinction, but _traversy_ doesn't at the moment.

I.e. currently
```clojure 
(view {} (l/in [:a])) => [nil]
(view {:a nil} (l/in [:a]) => [nil]
```

I propose that
```clojure
(view {} (l/in [:a])) => [] ;; this means 'No corresponding values were found'
(view {:a nil} (l/in [:a]) => [nil] ;; this means 'A value was found and it was nil'
```

I think this would make the interface more consistent, where any given lens acts as a selector that returns any values that it is able to find within the data.

**Comment by ctford** [comment]
The source of this behaviour seems to be the `in` lens.

```
(defn in
  "A lens from map -> value at path."
  ([path]
   (in path nil))
  ([path not-found]
   (lens (fn [x] (list (get-in x path not-found))) (partial fapply-in path))))
```

Would I be correct in understanding that it's the first clause that would change if we adopt your suggestion?

**Comment by johncowie** [comment]
I raised the issue before reading through the code :-p - wanted to get confirmation that there was actually something to fix before branching to fix it.

But I think a little more than the first clause would need to change.  The `fapply-in` function in the _fmap_ part of the lens looks right to me, and looks like this: 

``` clojure
(defn ^:no-doc fapply-in [path f x]
  (if (not= (get-in x path ::not-found) ::not-found)
    (update-in x path f)
    x))
```

The _focus_ part of the lens should work the same way.  E.g. something like:

``` clojure
(defn in [path]
  (lens
    (fn [x] (let [v (get-in x path ::not-found)] (if (= v ::not-found) (list) (list x))))
    (partial fapply-in path)))
```

I'll code this up in a branch with some tests, and link it to here.

**Comment by ctford** [comment]
I wonder if it would be possible to combine the *in *lens with one checking
the *contains? *predicate.

**Comment by johncowie** [comment]
Yes that's possible. That would look something like this:

``` clojure
(defn contains-path? [x path]
  (not= ::not-found (get-in x path ::not-found)))

(defn my-in [path] (*> (conditionally #(contains-path? % path)) (in path))
```

In this case `my-in` would indeed behave the way I want `in` to behave.

However I think this would still leave `in` as a constructor for "broken" lenses.  I feel like there should be a law(?) which says that for any given lens, the number of elements that _f_ is applied to when `update` is called should be the same as the number of elements returned if `view` is called.

To demonstrate in a slightly contrived way:

``` clojure
(let [counter (atom 0)
      id-count (fn [x] (swap! counter inc) x) ;; increment counter each time this function is applied
      l (in [:foo])]
  (-> {} (update l id-count))
  (= @counter (-> {} (view l) count))) ;; currently returns false
```

**Comment by johncowie** [comment]
Proposed change: https://github.com/ctford/traversy/commit/fec9dd7d348feed6ab6a0a4c5b4e54d3777b513a

NB: with this change, view-single will throw an assertion error if the path doesn't exist because zero values are found.

**Comment by ctford** [comment]
I agree that the current situation is inconsistent. If there's going to be a `::not-found` guard on update, it should be on view as well. In general, I think you're right that there should be the same focuses on `view` and `update`.

Your branch looks good to me, so I'm happy for you to merge.
